/**
 * Auto-generated by bin/fetch-library-keys.mjs — do not edit by hand.
 * Regenerate when the Web UI Kit or Colours/Themes libraries change.
 *
 * Initial seed is empty. Run from repo root:
 *   FIGMA_TOKEN=figd_xxx node bin/fetch-library-keys.mjs
 */
export type LibraryStyleEntry = { key: string; name: string; source: string };

export const LIBRARY_TEXT_STYLES: LibraryStyleEntry[] = [];

export const LIBRARY_PAINT_STYLES: LibraryStyleEntry[] = [];
