/**
 * Auto-generated by bin/fetch-library-keys.mjs — do not edit by hand.
 * Regenerate when the Web UI Kit or Colours/Themes libraries change.
 */
export type LibraryStyleEntry = { key: string; name: string; source: string };

export const LIBRARY_TEXT_STYLES: LibraryStyleEntry[] = [
  {
    "key": "275b26c81a11f4f620ad08b99ff5cb89ff7ba15b",
    "name": "8xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "3a1a964ca381b31bc0dd9aff852dcb322e2c95d0",
    "name": "2xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "1d1f12b8cc4f5d20ea95000bda109030cc3865f6",
    "name": "lg/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "376aa19905066cb3a201873f9462831fd0be8b13",
    "name": "base/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "e92c4f4a4fc375eb36d44d2d6a1781abd47fb029",
    "name": "base/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "f4aab2d37f00676cc8c8af24eba8e978ea5ff0e9",
    "name": "xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "d179cf8d2c51eed64413116c94a9f6dc12b1df80",
    "name": "sm/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "14aacfff58a5eed80b1df29bde17912b0294896e",
    "name": "4xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "e4431cfdbbe34c8712d05c09af62d7c6b7bb5317",
    "name": "xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "dec76adfee9e46fbaee4dba238b2b0dfbfb5b792",
    "name": "7xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "dedbb51f5554da10053ddff54a9c1f25aa924dfc",
    "name": "2xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "b0d39482d553fc34de8bfffcc2b6d8b7231a8042",
    "name": "xs/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "62c9a6e21f91e1780d5ee4fb3e4568f81575dd0a",
    "name": "4xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "cf987ea2a80b5c9da926ebb9c5818c3084b07bc9",
    "name": "2xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "042a3b57c26f52df2809c8c899b292da18661c1f",
    "name": "lg/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "84aba4ddbf8b6767a4a4bc49c04071fbe19c166f",
    "name": "4xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "17d80f8cefa39b4c91a0e6d85de0f66974ef64cd",
    "name": "base/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "d656ce46d2351d0a2009fa4ef480d5ecd4de6902",
    "name": "2xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "7d3ddbcd67a9b260501da0f40b053b4391f58c5c",
    "name": "3xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "8f4f2cafea13aee5b30f2b91b01d02257be2cfe7",
    "name": "3xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "4ca4ed4ea25bfdaae350f0b586bdea1aeeb65fc2",
    "name": "5xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "80859883deb562cbbe2b863963d6527a56eef056",
    "name": "sm/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "468e56686408f2f6bf49282610414e4e167aba4e",
    "name": "6xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "0a7ef2c4013ba35d8abeb3ed0a27e5f3f2316f2d",
    "name": "6xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "830a961fbd80ad64bd86727a31d2129f2d9cd245",
    "name": "6xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "53e155c72ff8829177c346700bbe3842b23cead3",
    "name": "7xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "94f463a7944a4d34b8a68f45ad395833acc043fe",
    "name": "3xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "da3d18270ae44e6de39f6909700adf3188e2dc5e",
    "name": "xs/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "28b54d73743ae041f36f2efcaf40173d82e3f3e1",
    "name": "xs/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "2c48e3dfdf74ba31e42f75d6c8e209e81c7c3412",
    "name": "xs/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "d174edf426a55e1ff21c8f9ec335b0186496e1db",
    "name": "sm/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "4eaac9a8a123366ec539a6fdb324a35c0be9a962",
    "name": "3xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "4292643e62aacd439f2d33943e4b48a4ca39801e",
    "name": "sm/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "894110b2a202f41982b92f3e0c8b14c7f6bed3d6",
    "name": "5xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "3cad55e7c445c884d96ca2dd87b5d361285367f4",
    "name": "4xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "be8c427ebb152d12c60f98cb2184f849250b41a9",
    "name": "5xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "eabb31d5906e6cc480ac130de314eba4f2f58e1d",
    "name": "5xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "4cdd344267f8414918e4a0e2797f861d3b44e760",
    "name": "6xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "2851963c355d7a9885daf9e4a4bf8ae9d737958b",
    "name": "7xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "5f48aef24f4ecfa39375bcabe87cabe3db1a1135",
    "name": "8xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "ffff67a7a983782b056451626062b9161f0b2e44",
    "name": "8xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "3150250c6120324431da7298a7cba0f1780b4363",
    "name": "8xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "2d39504a0b8708e0ea6c2b04e24767b0b37a01b3",
    "name": "base/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "91b74070297e1d110a38c29a056385341b12ef87",
    "name": "9xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "84b0a10ebcafd2aa48b0eadfb5a0144918f5aedb",
    "name": "lg/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "fe985c83266b85522a48a7725cb294b0977e96c9",
    "name": "9xl/semibold",
    "source": "Web UI Kit"
  },
  {
    "key": "5b146389166b8de89975882db23387a4038610b4",
    "name": "9xl/bold",
    "source": "Web UI Kit"
  },
  {
    "key": "49a93b71d58d499a43272d772f78234bb7e9b8bc",
    "name": "xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "e7e2fe11cd798cd20455eb5bdbf2724fc43092eb",
    "name": "xl/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "8fb3678013fce585cde135427bdefefe70a62208",
    "name": "lg/normal",
    "source": "Web UI Kit"
  },
  {
    "key": "75f2422834763dfb377beb48f818a323db9bbf73",
    "name": "9xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "1e972818c09a05195441b68b6cc9baf823083a99",
    "name": "7xl/medium",
    "source": "Web UI Kit"
  },
  {
    "key": "392d07aad2d83c4ab6614fe061de0c5a09e86110",
    "name": "5xl/brand",
    "source": "Web UI Kit"
  },
  {
    "key": "d0b9a16730fc9fd808c8b25fd00375cf5828682c",
    "name": "4xl/brand",
    "source": "Web UI Kit"
  }
];

export const LIBRARY_PAINT_STYLES: LibraryStyleEntry[] = [];
